<<<<<<< HEAD
echo "Hello World"
=======
echo "Hello World!"
>>>>>>> new_branch

Nueva Tabla
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID NUMBER(8),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25),
EMAIL VARCHAR2(25),
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE,
JOB_ID VARCHAR2(10),
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER (6),
DEPARTAMENT_ID NUMBER(4))

SELECT *FROM EMPLOYEES;
CREATE INDEX index ON EMPLOYEES (SALARY NOT NULL);